# Generated by Django 5.1 on 2025-08-08 08:56

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event", "0001_initial"),
        ("volunteers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventWithSchedule",
            fields=[
                (
                    "eventwithvolunteers_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="volunteers.eventwithvolunteers",
                    ),
                ),
                (
                    "slot_duration_schedule",
                    models.DurationField(default=datetime.timedelta(seconds=1800)),
                ),
            ],
            bases=("volunteers.eventwithvolunteers",),
        ),
        migrations.CreateModel(
            name="EventSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("saved_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("G", "generated"),
                            ("U", "user"),
                            ("B", "base"),
                            ("E", "empty"),
                        ],
                        default="U",
                        max_length=3,
                    ),
                ),
                ("deletable", models.BooleanField(default=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "based_on",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizer.eventschedule",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizer.eventwithschedule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventScheduleSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("position", models.IntegerField(default=0)),
                ("fixed", models.BooleanField(default=False)),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="event.role",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizer.eventschedule",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="volunteers.volunteeravailability",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleEventRemainder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days_before", models.IntegerField(default=15)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizer.eventwithschedule",
                    ),
                ),
            ],
        ),
    ]
