# Generated by Django 5.1 on 2025-08-08 08:56

import datetime

import django.db.models.deletion
import phonenumber_field.modelfields
import volunteers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventWithVolunteers",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="event.event",
                    ),
                ),
                (
                    "slot_duration_volunteer",
                    models.DurationField(default=datetime.timedelta(seconds=1800)),
                ),
                (
                    "convention",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=volunteers.models.event_directory_path,
                    ),
                ),
            ],
            bases=("event.event",),
        ),
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=200)),
                ("lastname", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                (
                    "phonenumber",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=20, null=True, region="FR"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VolunteerAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maxslot", models.IntegerField(default=1)),
                ("notes", models.TextField(blank=True, null=True)),
                ("categories", models.ManyToManyField(to="event.rolecategory")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="volunteers.eventwithvolunteers",
                    ),
                ),
                (
                    "friend",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="volunteers.volunteeravailability",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="volunteers.volunteer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="eventwithvolunteers",
            name="volunteers",
            field=models.ManyToManyField(
                through="volunteers.VolunteerAvailability", to="volunteers.volunteer"
            ),
        ),
        migrations.CreateModel(
            name="VolunteerFriendshipWaiting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=200)),
                ("lastname", models.CharField(max_length=200)),
                (
                    "volunteeravailability",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="volunteers.volunteeravailability",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VolunteerSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "availability",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="volunteers.volunteeravailability",
                    ),
                ),
            ],
        ),
    ]
