name: format & lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: ["3.12"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install tox
        run: python -m pip install tox
      - name: Run autoflake
        run: tox -e autoflake
      -name: Run isort
        run: tox -e isort
      -name: Run black
        run: tox -e black
      -name: Run flake8
        run: tox -e flake8

