name: test, format and lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: ["3.12"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install tox
        run: python -m pip install tox
      - name: Run tox
        run: tox
      - name: Publish coverage
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./build/coverage.xml
          junitxml-path: ./build/tests.xml

  format:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: ["3.12"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install tox
        run: python -m pip install tox
      - name: Run autoflake
        run: tox -e autoflake
      - name: Run isort
        run: tox -e isort
      - name: Run black
        run: tox -e black
      - name: Check if something has changed
        run: ./check_format.sh
  
  lint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: ["3.12"]
    needs: format
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install tox
        run: python -m pip install tox
      - name: Run flake8
        run: tox -e flake8
  


